name: ci-coverage
on: [push]

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: 🔢 Code Coverage
        uses: php-actions/phpunit@v2
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: ./coverage.xml
          args: --coverage-text
        env:
          TEST_NAME: main
          XDEBUG_MODE: coverage
          HUAWEI_CLIENT_ID: ${{ secrets.HUAWEI_CLIENT_ID }}
          HUAWEI_CLIENT_SECRET: ${{ secrets.HUAWEI_CLIENT_SECRET }}
          HUAWEI_UPLINK_HMAC: ${{ secrets.HUAWEI_UPLINK_HMAC }}
