name: CI
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: main
          HUAWEI_CLIENT_ID: ${{ secrets.HUAWEI_CLIENT_ID }}
          HUAWEI_CLIENT_SECRET: ${{ secrets.HUAWEI_CLIENT_SECRET }}
          HUAWEI_UPLINK_HMAC: ${{ secrets.HUAWEI_UPLINK_HMAC }}
        with:
          bootstrap: vendor/autoload.php
          configuration: ./phpunit.xml
          args: --coverage-text
